### ISSUE TITLE
Is Spain supported?

### ISSUE THREAD

**Issue by jbroudou** [jurajmajer/enrico#13]
According to the Supported country list it should be
https://github.com/jurajmajer/enrico/blob/4513277fd86b65031d268e8fdbd64d239910d8cb/holiday_library/SupportedCountry.php

However when hitting the API getSupportedCountries method, it does not return Spain.

**Comment by jurajmajer** [comment]
Hi,

Spain is not supported. The list of supported countries can be found in docu: http://holidays.kayaposoft.com/. This site actually calls API method getSupportedCountries.

You probably misunderstood the meaning of $fullNames property in SupportedCountry class. It contains full names of ALL countries in the world, not just supported ones.

However I would like to add Spain public holidays to the list in the future. Many people ask for it.
