### ISSUE TITLE
Date and/or name modification (Early May bank holiday Subdivision: GB-NIR / Year: 2020)

### ISSUE THREAD

**Issue by jbroudou** [jurajmajer/enrico#15]
It appears from https://www.gov.uk/bank-holidays#northern-ireland that in 2020 in Northern Ireland, "Early May bank holiday" has been moved from 2020-05-04 (Monday) to 2020-05-08 (Friday), and been renamed in this year, "Early May bank holiday (VE day)".

Your project is currently recording 2020-05-04 (Monday) as Early May bank holiday.

**Comment by jurajmajer** [comment]
I have changed it for England, Scotland and Wales as well as stated on https://www.gov.uk/bank-holidays
