### ISSUE TITLE
API to determine if a day is a working day

### ISSUE THREAD

**Issue by lpgera** [jurajmajer/enrico#2]
Hello!

Could you please make an API for querying whether a specific day is a workday in a country or not? Almost like the `isPublicHoliday` action, but taking in account extra workdays too.
Correct me if I'm wrong, but with the current API I can only use `getPublicHolidaysForDateRange` to extract this information.

Thank you!

**Comment by jurajmajer** [comment]
I have added new action `isWorkDay` to JSON and SOAP API.

**Comment by lpgera** [comment]
Perfect! Thanks! 👍
