### ISSUE TITLE
Request: Next Workday

### ISSUE THREAD

**Issue by BOSS1977-repo** [jurajmajer/enrico#41]
Hi,

Can you also add a Next Workday to the Open API specs? So you call the function with a startDate and a number of Workdays in the past of future, lets call it daysDalta (integer value minus to plus range). And then with the Workdays and holidays you can calculate the next day and of course a country the know whick holidays to use.

For example say my **startDate = 20-12-2024** and **daysDelta = +4** (days) and Country is **'NLD'** then the function NextWorkday returns the workday: **30-12-2024** 
_since 21 & 22 and also 28 & 29 are Weekends and 25 & 26 are holidays_

other example: 
 **startDate = 20-12-2024** and **daysDelta = -6** (days) and Country is **'NLD'** then the function NextWorkday returns the workday: **12-12-2024** 
_since 14 & 15 are Weekends_

Thx! Ciao Berend

**Comment by jurajmajer** [comment]
I have commited this feature in commit [1ecbc66](https://github.com/jurajmajer/enrico/commit/1ecbc6625589e5008ea8166030aef660b9b64da7). 
Feel free to report any problems or issues.
