### ISSUE TITLE
Error version 1.0 WSDL 

### ISSUE THREAD

**Issue by mstryck2** [jurajmajer/enrico#43]
Fatal error: Uncaught Error: Attempt to assign property "soap_defencoding" on bool in /data/e/b/eb10d60b-d905-44df-a47d-d71d172d115c/kayaposoft.com/web/enrico/ws/v1.0/index.php:11 Stack trace: #0 {main} thrown in /data/e/b/eb10d60b-d905-44df-a47d-d71d172d115c/kayaposoft.com/web/enrico/ws/v1.0/index.php on line 11

**Comment by jurajmajer** [comment]
It should be fixed now. 
Feel free to report any problems!
