### ISSUE TITLE
API not returning all entries shown on website

### ISSUE THREAD

**Issue by ditorelo** [jurajmajer/enrico#44]
Hey team, big fan of your service here!

I'm integrating our app with it and notice a discrepancy that I can't figure out how to solve. 

When looking for the full view for Australia in the website, I get a very good list, but when I request from the API, I only get 3 holidays come back. 

Full view for Australia
https://holidays.kayaposoft.com/public_holidays.php?year=2024&country=aus&region=act

API request
https://kayaposoft.com/enrico/json/v3.0/getHolidaysForYear?holidayType=all&country=aus&year=2024

Any idea why that could be?
Thanks!

**Comment by jurajmajer** [comment]
Hi Diogo,

in API request you should add also **region** query parameter. So the URL should like this:
https://kayaposoft.com/enrico/json/v3.0/getHolidaysForYear/?holidayType=all&country=aus&year=2024&region=act

When you do not specify the region param, Enrico service will return just dates which are the same for the whole Australia across all states. That is why it returns only 3 holidays.
