### ISSUE TITLE
"Parse error: Invalid numeric literal" on php 7.x

### ISSUE THREAD

**Issue by demaniak** [jurajmajer/enrico#5]
PHP Version 7.2.7

Running in container from [this image.](https://github.com/docker-library/php/blob/4af0a8734a48ab84ee96de513aabc45418b63dc5/7.2/stretch/apache/Dockerfile)

Any call produces this error:
```
Parse error: Invalid numeric literal in /var/www/html/holiday_library/utils/EquinoxUtils.php on line 10
```

**Comment by jurajmajer** [comment]
I have commited the fix. PHP 7 treats integers starting with 0 as octals. 
It should work now. If not, let me know.
