### ISSUE TITLE
README would useful

### ISSUE THREAD

**Issue by anuveyatsu** [jurajmajer/enrico#6]
It would be very useful to have a README so that users can understand which countries are covered here. I could create a bootstrap file if needed but I would appreciate if you could list all countries that are already covered. Many thanks in advance!

By using this [API endpoint](https://kayaposoft.com/enrico/json/v2.0/?action=getSupportedCountries) it looks like only 47 countries are covered. Is it correct?

**Comment by jurajmajer** [comment]
Yes, that's correct. All docu can be found here - https://kayaposoft.com/enrico/
