### ISSUE TITLE
New Holiday (March 8th) in Germany - Berlin

### ISSUE THREAD

**Issue by dirkam** [jurajmajer/enrico#8]
Hi,

March 8th (International Women's Day)
has been declared as an official holdiay in Berlin. [https://www.berlin.de/en/news/5600936-5559700-greens-give-final-green-light-for-new-ho.en.html](https://www.berlin.de/en/news/5600936-5559700-greens-give-final-green-light-for-new-ho.en.html)
Can you please update the list?

Thanks

**Comment by jurajmajer** [comment]
Hi dirkam,
i have updated the list. Thank you for helping me keep Enrico Service up-to-date.
